os: unstable
version: 0.0.3
branches:
  only:
    - master
cache:
  - node_modules
environment:
  nodejs_version: 6
install:
  - ps: Install-Product node $env:nodejs_version
  - set CI=true
  - npm install
build_script:
  - npm run build
test: off
